/*
 * Stub backport/autoconf.h for native Ubuntu kernel build
 *
 * This file is normally generated by the OpenWrt mac80211 backport system.
 * For native Ubuntu kernels (6.8+), we don't need backport compatibility
 * since the driver's version checks will use LINUX_VERSION_CODE directly.
 */

#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED

/* No backport-specific config needed for native kernel */

#endif /* COMPAT_AUTOCONF_INCLUDED */
